# Build settings
# github highlights with rouge and marks-up with kramdown (We used to use pygments and redcarpet)

# Site settings
title: "EdinbR: The Edinburgh R User Group"
description: > # this means to ignore newlines until "email:"
   Local <a href='https://www.meetup.com/EdinbR/'>meetups</a> and training for the R programming language

email: edinbr@proton.me
#blog logo
logo: "/assets/images/edinbr_300.png"
# blog cover
cover: "/assets/images/edin.png"

name: 'EdinbR'
author: 'EdinbR'
author_image: "/assets/images/edinbr_300.png"

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

url: "http://edinbr.org" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:

  - icon: group
    url:  https://groups.google.com/forum/#!forum/edinbr/join
    desc: Google groups
    
  - icon: comments
    url:  "https://app.element.io/#/room/#edinbr:matrix.org"
    desc: "#edinbr on Matrix"

  - icon: mastodon
    url: https://fosstodon.org/@EdinbR
    desc: Follow EdinbR on Mastondon

  - icon: 'meetup fa-1x'
    url:  https://www.meetup.com/EdinbR/
    desc: Meetup

  - icon: github
    url: https://github.com/EdinbR
    desc: EdinbR on Github
    share_url:
    share_title:
    share_link:

  - icon: envelope
    url:  mailto:edinbr@proton.me
    desc: email


#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:


# Disqus
comments:
   provider: disqus
disqus: 
   short_name: edinbr


